name: Build JSON from .alist

permissions:
  contents: write

on:
  push:
    paths:
      - 'air/data/**.alist'
      - 'air/data/airports.csv'
      - 'air/scripts/build_data.py'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Debug alt_codes parsing
        run: python air/scripts/debug_alt_codes.py

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Extract airport codes  # ✅ NEW STEP
        run: python air/scripts/extract_codes.py

      - name: Generate users.txt from manifest.json
        run: python air/scripts/generate_users_txt.py

      - name: Run build script
        run: python air/scripts/build_data.py

      - name: Check for unknown airport codes
        run: python air/scripts/check_unknown_codes.py

      - name: Show modified files
        run: |
          git status
          git diff --name-only

      - name: Commit all modified files safely
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A
          git commit -m "Auto-commit modified files from build" || echo "Nothing to commit"
          git pull --rebase origin master
          git push

      - name: Commit and push updated JSON
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git pull --rebase origin master
          git add air/data/*.json
          git commit -m "Auto-update JSON from .alist" || echo "Nothing to commit"
          git push origin master
