name: CSV and HTML Watchdog

on:
  push:
    paths:
      - 'airports.csv'
      - 'airports.html'
  workflow_dispatch:

jobs:
  validate-files:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout code
        uses: actions/checkout@v3

      - name: 🔍 Validate airports.csv
        run: |
          echo "Checking airports.csv..."
          awk -F';' '
            NF != 6 {
              print "❌ Line " NR " has " NF " fields (expected 6): " $0;
              exit 1
            }
          ' airports.csv
          echo "✅ CSV is structurally valid."

      - name: 🧪 Lint HTML with tidy
        run: |
          sudo apt-get install -y tidy
          tidy -q -e airports.html || echo "✅ HTML tidy check completed."
